PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX ngsi: <http://www.semanticweb.org/neclab/smartsantander/NGSI#>
SELECT ?attribute WHERE {?attribute rdfs:subPropertyOf ngsi:hasAttribute .
                                             ?attribute rdfs:domain ?type .
			{ SELECT ?type WHERE {ngsi:TempSensor rdfs:subClassOf* ?type } }
}